### ISSUE TITLE
This is already built into the game?

### ISSUE THREAD

**Issue by MrRagtime** [Nixuge/NoMoreWeather#1]
![image](https://github.com/Nixuge/NoMoreWeather/assets/134163817/b388d7d6-eaf7-4f4e-8a27-5a9e4fa69b9f)

**Comment by MrRagtime** [comment]
It's not built into vanilla minecraft but its already in optifine which makes this mod pointless.

**Comment by Nixuge** [comment]
- "When rain is OFF the splahes and rain sounds are still active". This mod disables the rain/thunder COMPLETELY from the game's pov
- Optifine is an absolute shithole to inject into from other mods, even with its source freely available you basically can't use mixins and have to use some assembly modifier, so some specialized mods (eg my superchargedchunkloading) aren't really compatible with it (or at least GREATLY limited)

**Comment by DrRagtime** [comment]
Still, why is this even a feature in the first place?
